// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package entity

const TableNameFavorite = "favorites"

// Favorite mapped from table <favorites>
type Favorite struct {
	FavoriteID int64 `gorm:"column:favorite_id;primaryKey;autoIncrement:true" json:"favorite_id"`
	UserID     int64 `gorm:"column:user_id;primaryKey" json:"user_id"`
	VideoID    int64 `gorm:"column:video_id;primaryKey" json:"video_id"`
	CreateTime int64 `gorm:"column:create_time" json:"create_time"`
}

// TableName Favorite's table name
func (*Favorite) TableName() string {
	return TableNameFavorite
}
