// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package entity

const TableNameFollow = "follows"

// Follow mapped from table <follows>
type Follow struct {
	FollowID   int64 `gorm:"column:follow_id;primaryKey;autoIncrement:true" json:"follow_id"`
	FollowbyID int64 `gorm:"column:followby_id;primaryKey" json:"followby_id"`
	FollowerID int64 `gorm:"column:follower_id;primaryKey" json:"follower_id"`
	CreateTime int64 `gorm:"column:create_time" json:"create_time"`
}

// TableName Follow's table name
func (*Follow) TableName() string {
	return TableNameFollow
}
