// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package entity

const TableNameUser = "users"

// User mapped from table <users>
type User struct {
	UserID          int64  `gorm:"column:user_id;primaryKey;autoIncrement:true" json:"user_id"`
	Username        string `gorm:"column:username" json:"username"`
	Password        string `gorm:"column:password" json:"password"`
	CreateTime      int64  `gorm:"column:create_time" json:"create_time"`
	Token           string `gorm:"column:token" json:"token"`
	TokenUpdateTime int64  `gorm:"column:token_update_time" json:"token_update_time"`
	Avatar          string `gorm:"column:avatar" json:"avatar"`
	BackgroundImage string `gorm:"column:background_image" json:"background_image"`
	FollowCount     int64  `gorm:"column:follow_count" json:"follow_count"`
	FollowerCount   int64  `gorm:"column:follower_count" json:"follower_count"`
	FavoriteCount   int64  `gorm:"column:favorite_count" json:"favorite_count"`
	WorkCount       int64  `gorm:"column:work_count" json:"work_count"`
}

// TableName User's table name
func (*User) TableName() string {
	return TableNameUser
}
