// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package entity

const TableNameVideo = "videos"

// Video mapped from table <videos>
type Video struct {
	VideoID       int32  `gorm:"column:video_id" json:"video_id"`
	UserID        int64  `gorm:"column:user_id" json:"user_id"`
	Token         string `gorm:"column:token" json:"token"`
	CreateAt      int64  `gorm:"column:create_at" json:"create_at"`
	PlayURL       string `gorm:"column:play_url" json:"play_url"`
	CoverURL      string `gorm:"column:cover_url" json:"cover_url"`
	FavoriteCount int64  `gorm:"column:favorite_count" json:"favorite_count"`
	CommentCount  int64  `gorm:"column:comment_count" json:"comment_count"`
	Title         string `gorm:"column:title" json:"title"`
}

// TableName Video's table name
func (*Video) TableName() string {
	return TableNameVideo
}
